name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */4 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: "Europe/Bucharest"
  github-stars:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: "Europe/Bucharest"
          plugin_stars: yes
          plugin_stars_limit: 6
          filename: github-stars.*
  github-achievements:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: "Europe/Bucharest"
          plugin_achievements: yes
          plugin_achievements_display: compact
          filename: github-achievements.*
